/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Fec;
import static java.lang.Math.pow;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hhurtado
 */
public class Formulario extends javax.swing.JFrame {

    private int iElementMemoria = 0;
    private int iXOR = 0;
    private int iSalida = 0;
    private int iCantEcuaciones = 0;
    private int[][] iTabla = null;
    private String[] iEstados = null;
    private String[] aEcuacion = null;
    private Fec oFec = null;

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        this.fnReiniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDialogTablaVerdad = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTVerdad = new javax.swing.JTable();
        jDialogEstados = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableEstados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanelVariables = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbElementosDeMemoria = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        sltXor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        sltSalidas = new javax.swing.JComboBox<>();
        btnCapturar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelMensaje = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnCodificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textMensaje = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textBit = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        textCodificado = new javax.swing.JTextArea();
        jPanelEcuaciones = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sltEcuacion3 = new javax.swing.JComboBox<>();
        btnIngresar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sltEcuacion1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        sltEcuacion4 = new javax.swing.JComboBox<>();
        sltEcuacion2 = new javax.swing.JComboBox<>();
        btnGenerarTabla = new javax.swing.JButton();
        jLabelNum = new javax.swing.JLabel();
        btnVerTabla = new javax.swing.JButton();
        jError = new javax.swing.JLabel();
        jError1 = new javax.swing.JLabel();
        btnEstados = new javax.swing.JButton();

        JDialogTablaVerdad.setMinimumSize(new java.awt.Dimension(600, 400));

        tableTVerdad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableTVerdad);

        javax.swing.GroupLayout JDialogTablaVerdadLayout = new javax.swing.GroupLayout(JDialogTablaVerdad.getContentPane());
        JDialogTablaVerdad.getContentPane().setLayout(JDialogTablaVerdadLayout);
        JDialogTablaVerdadLayout.setHorizontalGroup(
            JDialogTablaVerdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogTablaVerdadLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        JDialogTablaVerdadLayout.setVerticalGroup(
            JDialogTablaVerdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogTablaVerdadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialogEstados.setMinimumSize(new java.awt.Dimension(600, 400));

        tableEstados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tableEstados);

        javax.swing.GroupLayout jDialogEstadosLayout = new javax.swing.GroupLayout(jDialogEstados.getContentPane());
        jDialogEstados.getContentPane().setLayout(jDialogEstadosLayout);
        jDialogEstadosLayout.setHorizontalGroup(
            jDialogEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEstadosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jDialogEstadosLayout.setVerticalGroup(
            jDialogEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEstadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("CODIFICADOR FEC");

        jLabel2.setText("Seleccione cantidad de elementos de memoria:");

        cmbElementosDeMemoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cmbElementosDeMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbElementosDeMemoriaActionPerformed(evt);
            }
        });

        jLabel11.setText("Seleccione cantidad de XOR:");

        sltXor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));
        sltXor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sltXorActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccione cantidad de salidas:");

        sltSalidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        btnCapturar.setText("Capturar datos");
        btnCapturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturarActionPerformed(evt);
            }
        });

        jButton1.setText("Reiniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVariablesLayout = new javax.swing.GroupLayout(jPanelVariables);
        jPanelVariables.setLayout(jPanelVariablesLayout);
        jPanelVariablesLayout.setHorizontalGroup(
            jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVariablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sltSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelVariablesLayout.createSequentialGroup()
                        .addGroup(jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbElementosDeMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sltXor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCapturar)
                            .addComponent(jButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVariablesLayout.setVerticalGroup(
            jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVariablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbElementosDeMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sltXor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapturar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sltSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Digite mensaje a codificar con el sistema:");

        btnCodificar.setText("Codificar");
        btnCodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodificarActionPerformed(evt);
            }
        });

        textMensaje.setColumns(20);
        textMensaje.setRows(5);
        jScrollPane2.setViewportView(textMensaje);

        textBit.setColumns(20);
        textBit.setRows(5);
        jScrollPane3.setViewportView(textBit);

        textCodificado.setColumns(20);
        textCodificado.setRows(5);
        jScrollPane4.setViewportView(textCodificado);

        javax.swing.GroupLayout jPanelMensajeLayout = new javax.swing.GroupLayout(jPanelMensaje);
        jPanelMensaje.setLayout(jPanelMensajeLayout);
        jPanelMensajeLayout.setHorizontalGroup(
            jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanelMensajeLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMensajeLayout.createSequentialGroup()
                        .addGroup(jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(btnCodificar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelMensajeLayout.setVerticalGroup(
            jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCodificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Describa las ecuaciones de las salidas:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("XOR");

        sltEcuacion3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "D1", "D2", "D3", "Ninguna" }));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Seleccione ninguno en los items en caso de que la operacion no contenga más XOR (debe haber minimo uno)");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("XOR");

        sltEcuacion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "D1", "D2", "D3" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("XOR");

        sltEcuacion4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "D1", "D2", "D3", "Ninguna" }));

        sltEcuacion2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "D1", "D2", "D3", "Ninguna" }));
        sltEcuacion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sltEcuacion2ActionPerformed(evt);
            }
        });

        btnGenerarTabla.setText("Generar Tabla de Verdad");
        btnGenerarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarTablaActionPerformed(evt);
            }
        });

        jLabelNum.setText("Ecuacion #1");

        btnVerTabla.setText("Ver Tabla de Verdad");
        btnVerTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTablaActionPerformed(evt);
            }
        });

        jError.setForeground(new java.awt.Color(204, 0, 0));

        jError1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jError1.setForeground(new java.awt.Color(204, 0, 0));

        btnEstados.setText("Estados");
        btnEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEcuacionesLayout = new javax.swing.GroupLayout(jPanelEcuaciones);
        jPanelEcuaciones.setLayout(jPanelEcuacionesLayout);
        jPanelEcuacionesLayout.setHorizontalGroup(
            jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEcuacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEcuacionesLayout.createSequentialGroup()
                        .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEcuacionesLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNum))
                            .addGroup(jPanelEcuacionesLayout.createSequentialGroup()
                                .addComponent(sltEcuacion1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(sltEcuacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(sltEcuacion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(sltEcuacion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnIngresar)
                        .addGap(31, 31, 31))
                    .addGroup(jPanelEcuacionesLayout.createSequentialGroup()
                        .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEcuacionesLayout.createSequentialGroup()
                                .addComponent(jError1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addGroup(jPanelEcuacionesLayout.createSequentialGroup()
                                    .addComponent(btnGenerarTabla)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnVerTabla)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEstados))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelEcuacionesLayout.setVerticalGroup(
            jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEcuacionesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sltEcuacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(sltEcuacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(sltEcuacion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresar)
                    .addComponent(jLabel10)
                    .addComponent(sltEcuacion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jError1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarTabla)
                    .addComponent(btnVerTabla)
                    .addComponent(btnEstados))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelEcuaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelVariables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelVariables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelEcuaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnCrearTabla() {
        this.oFec = new Fec(this.iElementMemoria, this.iSalida, this.iXOR, this.aEcuacion);
        this.iTabla = this.oFec.getTablaVerdad();
        this.iEstados = this.oFec.getEstados();
    }

    private void fnGenerarTabla() {
        int iAux = this.iElementMemoria;
        DefaultTableModel modelo = new DefaultTableModel(){
            public boolean isCellEditable(int rowIndex,int columnIndex){return false;}
        };
        this.tableTVerdad.setModel(modelo);
        // For para imprimir la matriz de prueba
        int iAux2 = 0;
        for (int i = 0; i < this.iTabla[0].length; i++) {
            if (i == 0) {
                modelo.addColumn("E");
            } else if (i < (iAux + 1)) {
                if (i == 1) {
                    iAux2 = 1;
                }
                modelo.addColumn("D" + iAux2 + "(Actual)");
                iAux2++;
            } else if (i >= (iAux + 1) && i < ((iAux * 2) + 1)) {
                if (i == (iAux + 1)) {
                    iAux2 = 1;
                }
                modelo.addColumn("D" + iAux2 + "(Siguiente)");
                iAux2++;
            } else {
                if (i == ((iAux * 2) + 1)) {
                    iAux2 = 1;
                }
                modelo.addColumn("S" + iAux2);
                iAux2++;
            }
        }
        for (int i = 0; i < this.iTabla.length; i++) {
            Object[] fila = new Object[this.iTabla[i].length];
            for (int j = 0; j < this.iTabla[i].length; j++) {
                fila[j] = this.iTabla[i][j];
                System.out.print("|" + this.iTabla[i][j] + "|");
            }
            System.out.println("");
            modelo.addRow(fila);
        }
        this.JDialogTablaVerdad.show();
    }

    private void cmbElementosDeMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbElementosDeMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbElementosDeMemoriaActionPerformed

    private void sltXorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sltXorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sltXorActionPerformed

    private void btnGenerarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarTablaActionPerformed
        this.fnCrearTabla();
        this.btnGenerarTabla.setEnabled(false);
        this.btnVerTabla.setEnabled(true);
        this.btnEstados.setEnabled(true);
        this.textMensaje.setEnabled(true);
        this.btnCodificar.setEnabled(true);
    }//GEN-LAST:event_btnGenerarTablaActionPerformed

    public String fnConvertirTextBit(String recibido) {
        //calculo el tamaño de la cadena
        int longitud = recibido.length();
        //creo un array char con el string anterior
        char cadChar[] = recibido.toCharArray();
        //inicializo varibles a utilizar en el ciclo
        String charBin = "";
        //ciclo que me convierte cada letra en binario
        for (int i = 0; i < cadChar.length; i++) {
            //convierto a binario cada caracter
            charBin += String.format("%8s", Integer.toBinaryString(cadChar[i])).replace(" ", "0");
        }
        return charBin;
    }
    
    public String fnConvertirBitText(String recibido) {
        String frase = "";//almacena la frase completa
        for (int i = 0; i < recibido.length(); i += 8) {//recorre la frase de 8 en 8
            /*separa la cadena cada 8 digitos con substring*/
            /*entrega un numero decimal a partir de un numero binario de 8 bit*/
            /*concadena la frase y transfroma el decimal a Ascii*/
            frase += (char) Integer.parseInt(recibido.substring(i, i + 8), 2);
        }
        return frase;
    }

    private void sltEcuacion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sltEcuacion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sltEcuacion2ActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (this.fnValidar() > 0) {
            boolean bValidacion = this.fnCrearEcuacion();
            if (bValidacion) {
                this.iCantEcuaciones = this.iCantEcuaciones + 1;
                this.jLabelNum.setText("Ecuacion #" + (this.iCantEcuaciones + 1));
                this.jError.setText("");
                this.jError1.setText("");
                this.sltEcuacion1.setSelectedIndex(0);
                this.sltEcuacion2.setSelectedIndex(0);
                this.sltEcuacion3.setSelectedIndex(0);
                this.sltEcuacion4.setSelectedIndex(0);
            } else {
                this.jError1.setText("Error: ");
                this.jError.setText("No se ha seleccionado los XOR correctos");
            }
        } else {
            this.jError1.setText("Error: ");
            this.jError.setText("Debe seleccionar elementos");
        }
        if (this.iCantEcuaciones == this.iSalida) {
            this.btnIngresar.setEnabled(false);
            this.btnGenerarTabla.setEnabled(true);
            this.sltEcuacion1.setEnabled(false);
            this.sltEcuacion2.setEnabled(false);
            this.sltEcuacion3.setEnabled(false);
            this.sltEcuacion4.setEnabled(false);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed
    
    private boolean fnCrearEcuacion() {
        String sText = "";
        if (this.sltEcuacion1.getSelectedItem().toString() != "Ninguna") {
            if (sText == ""){
                sText += this.sltEcuacion1.getSelectedItem().toString();
            } else {
                sText += " XOR " + this.sltEcuacion1.getSelectedItem().toString();
            }
        }
        if (this.sltEcuacion2.getSelectedItem().toString() != "Ninguna") {
            if (sText == ""){
                sText += this.sltEcuacion2.getSelectedItem().toString();
            } else {
                sText += " XOR " + this.sltEcuacion2.getSelectedItem().toString();
            }
        }
        if (this.sltEcuacion3.getSelectedItem().toString() != "Ninguna") {
            if (sText == ""){
                sText += this.sltEcuacion3.getSelectedItem().toString();
            } else {
                sText += " XOR " + this.sltEcuacion3.getSelectedItem().toString();
            }
        }
        if (this.sltEcuacion4.getSelectedItem().toString() != "Ninguna") {
            if (sText == ""){
                sText += this.sltEcuacion4.getSelectedItem().toString();
            } else {
                sText += " XOR " + this.sltEcuacion4.getSelectedItem().toString();
            }
        }
        boolean bAux = false;
        aEcuacion[this.iCantEcuaciones] = sText;
        if ((this.iCantEcuaciones + 1) == this.iSalida) {
            String sXOR =  "XOR";
            int iAux = 0;
            for (int i = 0; i < aEcuacion.length; i++) {
                if (aEcuacion[i].contains(sXOR)) {
                    iAux++;
                }
            }
            if (iAux != this.iXOR) {
                bAux = false;
            } else {
                bAux = true;
            }
        } else {
            bAux = true;
        }
        if (!bAux) {
            aEcuacion[this.iCantEcuaciones] = "";
        }
        return bAux;
    }
    
    private int fnValidar() {
        int iAux = 0;
        if (this.sltEcuacion1.getSelectedItem().toString() != "Ninguna") {
            iAux++;
        }
        if (this.sltEcuacion2.getSelectedItem().toString() != "Ninguna") {
            iAux++;
        }
        if (this.sltEcuacion3.getSelectedItem().toString() != "Ninguna") {
            iAux++;
        }
        if (this.sltEcuacion4.getSelectedItem().toString() != "Ninguna") {
            iAux++;
        }
        return iAux;
    }
    
    private void btnCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarActionPerformed
        this.iElementMemoria = Integer.parseInt(this.cmbElementosDeMemoria.getSelectedItem().toString());
        this.iXOR = Integer.parseInt(this.sltXor.getSelectedItem().toString());
        this.iSalida = Integer.parseInt(this.sltSalidas.getSelectedItem().toString());
        aEcuacion = new String[this.iSalida];
        this.btnIngresar.setEnabled(true);
        this.cmbElementosDeMemoria.setEnabled(false);
        this.sltXor.setEnabled(false);
        this.sltSalidas.setEnabled(false);
        this.btnCapturar.setEnabled(false);
        this.sltEcuacion1.setEnabled(true);
        this.sltEcuacion2.setEnabled(true);
        this.sltEcuacion3.setEnabled(true);
        this.sltEcuacion4.setEnabled(true);
        this.sltEcuacion1.removeAllItems();
        this.sltEcuacion2.removeAllItems();
        this.sltEcuacion3.removeAllItems();
        this.sltEcuacion4.removeAllItems();
        this.fnAgregarItems(this.sltEcuacion1);
        this.fnAgregarItems(this.sltEcuacion2);
        this.fnAgregarItems(this.sltEcuacion3);
        this.fnAgregarItems(this.sltEcuacion4);
    }//GEN-LAST:event_btnCapturarActionPerformed
    
    private void fnAgregarItems(javax.swing.JComboBox<String> eSelect) {
        eSelect.addItem("Ninguna");
        eSelect.addItem("E");
        for (int i = 0; i < this.iElementMemoria; i++) {
            eSelect.addItem("D" + (i+1));
        }
    }
    
    private void btnVerTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTablaActionPerformed
        this.fnGenerarTabla();
    }//GEN-LAST:event_btnVerTablaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.fnReiniciar();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void fnReiniciar() {
        this.cmbElementosDeMemoria.setEnabled(true);
        this.sltXor.setEnabled(true);
        this.sltSalidas.setEnabled(true);
        this.btnCapturar.setEnabled(true);
        this.sltEcuacion1.setEnabled(false);
        this.sltEcuacion2.setEnabled(false);
        this.sltEcuacion3.setEnabled(false);
        this.sltEcuacion4.setEnabled(false);
        this.textBit.setEnabled(false);
        this.textCodificado.setEnabled(false);
        this.cmbElementosDeMemoria.setSelectedIndex(0);
        this.sltXor.setSelectedIndex(0);
        this.sltSalidas.setSelectedIndex(0);
        this.sltEcuacion1.setSelectedIndex(0);
        this.sltEcuacion2.setSelectedIndex(0);
        this.sltEcuacion3.setSelectedIndex(0);
        this.sltEcuacion4.setSelectedIndex(0);
        this.btnIngresar.setEnabled(false);
        this.btnGenerarTabla.setEnabled(false);
        this.textMensaje.setEnabled(false);
        this.btnCodificar.setEnabled(false);
        this.btnVerTabla.setEnabled(false);
        this.btnEstados.setEnabled(false);
        this.jLabelNum.setText("Ecuacion #1");
        this.textMensaje.setText("");
        this.textBit.setText("");
        this.textCodificado.setText("");
        this.iCantEcuaciones = 0;
        this.jError.setText("");
        this.jError1.setText("");
    }
    
    private void btnCodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodificarActionPerformed
        String sBinario = this.fnConvertirTextBit(this.textMensaje.getText());
        this.textBit.setText(sBinario);
        this.textCodificado.setText(this.oFec.getCodificar(sBinario));
//        String sTexto = this.fnConvertirBitText(sBinario);
//        System.out.println(sTexto);
    }//GEN-LAST:event_btnCodificarActionPerformed

    private void btnEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadosActionPerformed
        DefaultTableModel modelo = new DefaultTableModel(){
            public boolean isCellEditable(int rowIndex,int columnIndex){return false;}
        };
        this.tableEstados.setModel(modelo);
        int iEstados = (int) pow(2, this.iElementMemoria);
        // For para imprimir la matriz de prueba
        for (int i = 0; i < iEstados; i++) {
            modelo.addColumn("S°" + i);
        }
        Object[] fila = new Object[iEstados];
        for (int i = 0; i < this.iEstados.length; i++) {
            fila[i] = this.iEstados[i];
        }
        modelo.addRow(fila);
        this.jDialogEstados.show();
    }//GEN-LAST:event_btnEstadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JDialogTablaVerdad;
    private javax.swing.JButton btnCapturar;
    private javax.swing.JButton btnCodificar;
    private javax.swing.JButton btnEstados;
    private javax.swing.JButton btnGenerarTabla;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnVerTabla;
    private javax.swing.JComboBox<String> cmbElementosDeMemoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialogEstados;
    private javax.swing.JLabel jError;
    private javax.swing.JLabel jError1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JPanel jPanelEcuaciones;
    private javax.swing.JPanel jPanelMensaje;
    private javax.swing.JPanel jPanelVariables;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JComboBox<String> sltEcuacion1;
    private javax.swing.JComboBox<String> sltEcuacion2;
    private javax.swing.JComboBox<String> sltEcuacion3;
    private javax.swing.JComboBox<String> sltEcuacion4;
    private javax.swing.JComboBox<String> sltSalidas;
    private javax.swing.JComboBox<String> sltXor;
    private javax.swing.JTable tableEstados;
    private javax.swing.JTable tableTVerdad;
    private javax.swing.JTextArea textBit;
    private javax.swing.JTextArea textCodificado;
    private javax.swing.JTextArea textMensaje;
    // End of variables declaration//GEN-END:variables

}
