/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Fec;
import static java.lang.Math.pow;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hhurtado
 */
public class Formulario extends javax.swing.JFrame {

    private int iElementMemoria = 0;
    private int iXOR = 0;
    private int iSalida = 0;
    private int iCantEcuaciones = 0;
    private int[][] iTabla = null;
    private String[] iEstados = null;
    private String[] aEcuacion = null;
    private Fec oFec = null;
    private int iCapturaErrores = 0;
    private String sTextBitCod = "";

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        this.fnReiniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDialogTablaVerdad = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTVerdad = new javax.swing.JTable();
        jDialogEstados = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableEstados = new javax.swing.JTable();
        jDialogPropuesta = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtPropuesta = new javax.swing.JTextArea();
        JPanelContenedor = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelVariables = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbElementosDeMemoria = new javax.swing.JComboBox<String>();
        jLabel11 = new javax.swing.JLabel();
        sltXor = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        sltSalidas = new javax.swing.JComboBox<String>();
        btnCapturar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelEcuaciones = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sltEcuacion3 = new javax.swing.JComboBox<String>();
        btnIngresar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sltEcuacion1 = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        sltEcuacion4 = new javax.swing.JComboBox<String>();
        sltEcuacion2 = new javax.swing.JComboBox<String>();
        btnGenerarTabla = new javax.swing.JButton();
        jLabelNum = new javax.swing.JLabel();
        btnVerTabla = new javax.swing.JButton();
        jError = new javax.swing.JLabel();
        jError1 = new javax.swing.JLabel();
        btnEstados = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanelMensaje = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnCodificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textMensaje = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textBit = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        textCodificado = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDecodificado = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtEstadosSalidas = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        sltPalabras = new javax.swing.JComboBox<String>();
        jLabel13 = new javax.swing.JLabel();
        sltErroresCant = new javax.swing.JComboBox<String>();
        btnCapturarDec = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtAreaMsgError = new javax.swing.JTextArea();
        btnCorrerDec = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtAreaMsgCorre = new javax.swing.JTextArea();
        btnDecodificar = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtAreaMsgSol = new javax.swing.JTextArea();
        btnReiniciarDec = new javax.swing.JButton();
        jlblNumErrores = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        JDialogTablaVerdad.setMinimumSize(new java.awt.Dimension(600, 400));

        tableTVerdad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableTVerdad);

        javax.swing.GroupLayout JDialogTablaVerdadLayout = new javax.swing.GroupLayout(JDialogTablaVerdad.getContentPane());
        JDialogTablaVerdad.getContentPane().setLayout(JDialogTablaVerdadLayout);
        JDialogTablaVerdadLayout.setHorizontalGroup(
            JDialogTablaVerdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogTablaVerdadLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        JDialogTablaVerdadLayout.setVerticalGroup(
            JDialogTablaVerdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogTablaVerdadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialogEstados.setMinimumSize(new java.awt.Dimension(600, 400));

        tableEstados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tableEstados);

        javax.swing.GroupLayout jDialogEstadosLayout = new javax.swing.GroupLayout(jDialogEstados.getContentPane());
        jDialogEstados.getContentPane().setLayout(jDialogEstadosLayout);
        jDialogEstadosLayout.setHorizontalGroup(
            jDialogEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEstadosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jDialogEstadosLayout.setVerticalGroup(
            jDialogEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEstadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialogPropuesta.setMinimumSize(new java.awt.Dimension(651, 339));

        jLabel8.setText("PROPUESTA DE SISTEMA PARA CORREGIR CANTIDAD DE ERRORES DESEADA");

        txtPropuesta.setColumns(20);
        txtPropuesta.setRows(5);
        jScrollPane12.setViewportView(txtPropuesta);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogPropuestaLayout = new javax.swing.GroupLayout(jDialogPropuesta.getContentPane());
        jDialogPropuesta.getContentPane().setLayout(jDialogPropuestaLayout);
        jDialogPropuestaLayout.setHorizontalGroup(
            jDialogPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPropuestaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jDialogPropuestaLayout.setVerticalGroup(
            jDialogPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPropuestaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanelContenedor.setForeground(new java.awt.Color(0, 0, 204));
        JPanelContenedor.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CODIFICADOR FEC");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Seleccione cantidad de elementos de memoria:");

        cmbElementosDeMemoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        cmbElementosDeMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbElementosDeMemoriaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Seleccione cantidad de XOR:");

        sltXor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3" }));
        sltXor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sltXorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Seleccione cantidad de salidas:");

        sltSalidas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));

        btnCapturar.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnCapturar.setText("Capturar datos");
        btnCapturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton1.setText("Reiniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVariablesLayout = new javax.swing.GroupLayout(jPanelVariables);
        jPanelVariables.setLayout(jPanelVariablesLayout);
        jPanelVariablesLayout.setHorizontalGroup(
            jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVariablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3))
                .addGap(53, 53, 53)
                .addGroup(jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sltSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelVariablesLayout.createSequentialGroup()
                        .addGroup(jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbElementosDeMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sltXor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132)
                        .addGroup(jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCapturar)
                            .addComponent(jButton1))))
                .addGap(60, 60, 60))
        );
        jPanelVariablesLayout.setVerticalGroup(
            jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVariablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbElementosDeMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sltXor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapturar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sltSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Describa las ecuaciones de las salidas:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("XOR");

        sltEcuacion3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "E", "D1", "D2", "D3", "Ninguna" }));
        sltEcuacion3.setPreferredSize(new java.awt.Dimension(80, 20));

        btnIngresar.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Seleccione ninguno en los items en caso de que la operacion no contenga más XOR (debe haber minimo uno)");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("XOR");

        sltEcuacion1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "E", "D1", "D2", "D3" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("XOR");

        sltEcuacion4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "E", "D1", "D2", "D3", "Ninguna" }));
        sltEcuacion4.setPreferredSize(new java.awt.Dimension(80, 20));

        sltEcuacion2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "E", "D1", "D2", "D3", "Ninguna" }));
        sltEcuacion2.setPreferredSize(new java.awt.Dimension(80, 20));
        sltEcuacion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sltEcuacion2ActionPerformed(evt);
            }
        });

        btnGenerarTabla.setText("Generar Tabla de Verdad");
        btnGenerarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarTablaActionPerformed(evt);
            }
        });

        jLabelNum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNum.setForeground(new java.awt.Color(0, 0, 255));
        jLabelNum.setText("Ecuacion #1");

        btnVerTabla.setText("Ver Tabla de Verdad");
        btnVerTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTablaActionPerformed(evt);
            }
        });

        jError.setForeground(new java.awt.Color(204, 0, 0));

        jError1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jError1.setForeground(new java.awt.Color(204, 0, 0));

        btnEstados.setText("Estados");
        btnEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEcuacionesLayout = new javax.swing.GroupLayout(jPanelEcuaciones);
        jPanelEcuaciones.setLayout(jPanelEcuacionesLayout);
        jPanelEcuacionesLayout.setHorizontalGroup(
            jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEcuacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEcuacionesLayout.createSequentialGroup()
                        .addComponent(sltEcuacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sltEcuacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sltEcuacion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sltEcuacion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnIngresar))
                    .addGroup(jPanelEcuacionesLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNum))
                    .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEcuacionesLayout.createSequentialGroup()
                            .addComponent(jError1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanelEcuacionesLayout.createSequentialGroup()
                                .addComponent(btnGenerarTabla)
                                .addGap(18, 18, 18)
                                .addComponent(btnVerTabla)
                                .addGap(18, 18, 18)
                                .addComponent(btnEstados)))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanelEcuacionesLayout.setVerticalGroup(
            jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEcuacionesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sltEcuacion1)
                    .addComponent(sltEcuacion2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sltEcuacion3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(btnIngresar)
                        .addComponent(jLabel10)
                        .addComponent(sltEcuacion4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jError1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jError, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarTabla)
                    .addComponent(btnVerTabla)
                    .addComponent(btnEstados))
                .addContainerGap())
        );

        jPanelMensaje.setPreferredSize(new java.awt.Dimension(707, 305));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Digite mensaje a codificar con el sistema:");

        btnCodificar.setText("Codificar");
        btnCodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodificarActionPerformed(evt);
            }
        });

        textMensaje.setColumns(20);
        textMensaje.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        textMensaje.setForeground(new java.awt.Color(255, 0, 0));
        textMensaje.setRows(5);
        jScrollPane2.setViewportView(textMensaje);

        textBit.setColumns(20);
        textBit.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        textBit.setForeground(new java.awt.Color(255, 0, 0));
        textBit.setRows(5);
        jScrollPane3.setViewportView(textBit);

        textCodificado.setColumns(20);
        textCodificado.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        textCodificado.setForeground(new java.awt.Color(255, 0, 0));
        textCodificado.setRows(5);
        jScrollPane4.setViewportView(textCodificado);

        txtDecodificado.setColumns(20);
        txtDecodificado.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        txtDecodificado.setForeground(new java.awt.Color(255, 0, 0));
        txtDecodificado.setRows(5);
        jScrollPane5.setViewportView(txtDecodificado);

        txtEstadosSalidas.setColumns(20);
        txtEstadosSalidas.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        txtEstadosSalidas.setForeground(new java.awt.Color(255, 0, 0));
        txtEstadosSalidas.setRows(5);
        jScrollPane8.setViewportView(txtEstadosSalidas);

        javax.swing.GroupLayout jPanelMensajeLayout = new javax.swing.GroupLayout(jPanelMensaje);
        jPanelMensaje.setLayout(jPanelMensajeLayout);
        jPanelMensajeLayout.setHorizontalGroup(
            jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMensajeLayout.createSequentialGroup()
                        .addGroup(jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)))
                    .addGroup(jPanelMensajeLayout.createSequentialGroup()
                        .addGroup(jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(btnCodificar))
                        .addGap(0, 491, Short.MAX_VALUE))
                    .addComponent(jScrollPane8))
                .addContainerGap())
        );
        jPanelMensajeLayout.setVerticalGroup(
            jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCodificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane7.setViewportView(jPanelMensaje);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelVariables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelEcuaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelVariables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelEcuaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanelContenedor.addTab("Codificacion", jPanel1);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("Palabra seleccionada:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("Cantidad de errores:");

        sltErroresCant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));

        btnCapturarDec.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnCapturarDec.setText("Capturar error");
        btnCapturarDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturarDecActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Mensaje con error");

        txtAreaMsgError.setColumns(20);
        txtAreaMsgError.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        txtAreaMsgError.setForeground(new java.awt.Color(255, 0, 0));
        txtAreaMsgError.setRows(5);
        jScrollPane9.setViewportView(txtAreaMsgError);

        btnCorrerDec.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnCorrerDec.setText("Corregir errores");
        btnCorrerDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrerDecActionPerformed(evt);
            }
        });

        txtAreaMsgCorre.setColumns(20);
        txtAreaMsgCorre.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        txtAreaMsgCorre.setForeground(new java.awt.Color(255, 0, 0));
        txtAreaMsgCorre.setRows(5);
        jScrollPane10.setViewportView(txtAreaMsgCorre);

        btnDecodificar.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnDecodificar.setText("Decodificar");
        btnDecodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecodificarActionPerformed(evt);
            }
        });

        txtAreaMsgSol.setColumns(20);
        txtAreaMsgSol.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        txtAreaMsgSol.setForeground(new java.awt.Color(255, 0, 0));
        txtAreaMsgSol.setRows(5);
        jScrollPane11.setViewportView(txtAreaMsgSol);

        btnReiniciarDec.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnReiniciarDec.setText("Reiniciar");
        btnReiniciarDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarDecActionPerformed(evt);
            }
        });

        jlblNumErrores.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlblNumErrores.setForeground(new java.awt.Color(0, 0, 204));
        jlblNumErrores.setText("Errores # 0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9)
                    .addComponent(jScrollPane10)
                    .addComponent(jScrollPane11)
                    .addComponent(btnCorrerDec)
                    .addComponent(btnDecodificar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(107, 107, 107)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sltPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sltErroresCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addComponent(btnCapturarDec)
                                .addGap(34, 34, 34)
                                .addComponent(btnReiniciarDec))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 545, Short.MAX_VALUE)
                                .addComponent(jlblNumErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(sltPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(sltErroresCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jlblNumErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCapturarDec)
                            .addComponent(btnReiniciarDec))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCorrerDec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDecodificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("DECODIFICADOR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        JPanelContenedor.addTab("Decodificacion", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelContenedor)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelContenedor))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnCrearTabla() {
        this.oFec = new Fec(this.iElementMemoria, this.iSalida, this.iXOR, this.aEcuacion);
        this.iTabla = this.oFec.getTablaVerdad();
        this.iEstados = this.oFec.getEstados();
    }

    private void fnGenerarTabla() {
        int iAux = this.iElementMemoria;
        DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        this.tableTVerdad.setModel(modelo);
        // For para imprimir la matriz de prueba
        int iAux2 = 0;
        for (int i = 0; i < this.iTabla[0].length; i++) {
            if (i == 0) {
                modelo.addColumn("E");
            } else if (i < (iAux + 1)) {
                if (i == 1) {
                    iAux2 = 1;
                }
                modelo.addColumn("D" + iAux2 + "(Actual)");
                iAux2++;
            } else if (i >= (iAux + 1) && i < ((iAux * 2) + 1)) {
                if (i == (iAux + 1)) {
                    iAux2 = 1;
                }
                modelo.addColumn("D" + iAux2 + "(Siguiente)");
                iAux2++;
            } else {
                if (i == ((iAux * 2) + 1)) {
                    iAux2 = 1;
                }
                modelo.addColumn("S" + iAux2);
                iAux2++;
            }
        }
        for (int i = 0; i < this.iTabla.length; i++) {
            Object[] fila = new Object[this.iTabla[i].length];
            for (int j = 0; j < this.iTabla[i].length; j++) {
                fila[j] = this.iTabla[i][j];
                System.out.print("|" + this.iTabla[i][j] + "|");
            }
            System.out.println("");
            modelo.addRow(fila);
        }
        this.JDialogTablaVerdad.show();
    }

    //Funcion para sacar la distancia libre
    private boolean distanciaLibre() {

        // distancia libre > 2 t donde t es la cantidad de errores
        int tam = 0;
        boolean resultado = false;
        int distanciaLibre1 = 0;
        int distanciaLibre2 = 0;
        int distanciaLibre3 = 0;

        if (sltSalidas.getSelectedItem().equals("1")) {
            //Tiene una salida
            tam = this.iTabla[0].length - 1;
            //System.out.println("tamaño fila: " + tam);
            for (int i = 0; i < this.iTabla.length; i++) {
                int j = this.iTabla[i].length - 1;
                //System.out.println("Valor de la tabla: " + this.iTabla[i][j]);
//                    System.out.println("Empiezo en posicion: " + i + "," + j);
                if (this.iTabla[i][j] == 1) {
                    distanciaLibre1++;
                }
            }

//            System.out.println("Distancia Libre s1: " + distanciaLibre1);
            //System.out.println("Distancia Libre es : " + distanciaLibre1);
            if (distanciaLibre1 >= (2 * (Integer.parseInt(sltErroresCant.getSelectedItem().toString())))) {
                resultado = true;
            } else {
                resultado = false;
                JOptionPane.showMessageDialog(null, "NO es posible corregir " + sltErroresCant.getSelectedItem().toString() + " errores en este sistema", "Mensaje de Advertencia", JOptionPane.WARNING_MESSAGE);
                JOptionPane.showMessageDialog(null, "A continuacion un sistema ideal para la cantidad de errores deseados", "Mensaje informativo", JOptionPane.INFORMATION_MESSAGE);
            }

        } else if (sltSalidas.getSelectedItem().equals("2")) {
            //Tiene dos salidas
            tam = this.iTabla[0].length - 2;
//            System.out.println("tamaño fila: " + tam);

            for (int i = 0; i < this.iTabla.length; i++) {
                int j = this.iTabla[i].length - 1;
                //System.out.println("Valor de la tabla: " + this.iTabla[i][j]);
//                    System.out.println("Empiezo en posicion: " + i + "," + j);
                if (this.iTabla[i][j] == 1) {
                    distanciaLibre1++;
                }
                if (this.iTabla[i][j - 1] == 1) {
                    distanciaLibre2++;
                }
            }

//            System.out.println("Distancia Libre s1: " + distanciaLibre1);
//            System.out.println("Distancia Libre s2: " + distanciaLibre2);
            int distanciamenor = distanciaLibre1;
            if (distanciaLibre1 > distanciaLibre2) {
                distanciamenor = distanciaLibre2;
            }
//            System.out.println("Distancia Libre es : " + distanciamenor);
//            System.out.println("Errores a corregir : " + (2 * (Integer.parseInt(sltErroresCant.getSelectedItem().toString()))));
            if (distanciamenor >= (2 * (Integer.parseInt(sltErroresCant.getSelectedItem().toString())))) {
                resultado = true;
            } else {
                resultado = false;
                JOptionPane.showMessageDialog(null, "NO es posible corregir " + sltErroresCant.getSelectedItem().toString() + " errores en este sistema", "Mensaje de Advertencia", JOptionPane.WARNING_MESSAGE);
                JOptionPane.showMessageDialog(null, "A continuacion un sistema ideal para la cantidad de errores deseados", "Mensaje informativo", JOptionPane.INFORMATION_MESSAGE);

            }

        } else if (sltSalidas.getSelectedItem().equals("3")) {
            //Tiene tres salidas
            tam = this.iTabla[0].length - 3;
//            System.out.println("tamaño fila: " + tam);

            for (int i = 0; i < this.iTabla.length; i++) {
                int j = this.iTabla[i].length - 1;
                //System.out.println("Valor de la tabla: " + this.iTabla[i][j]);
//                    System.out.println("Empiezo en posicion: " + i + "," + j);
                if (this.iTabla[i][j] == 1) {
                    distanciaLibre1++;
                }
                if (this.iTabla[i][j - 1] == 1) {
                    distanciaLibre2++;
                }
                if (this.iTabla[i][j - 2] == 1) {
                    distanciaLibre3++;
                }

            }

//            System.out.println("Distancia Libre s1: " + distanciaLibre1);
//            System.out.println("Distancia Libre s2: " + distanciaLibre2);
//            System.out.println("Distancia Libre s3: " + distanciaLibre3);
            int distanciamenor = distanciaLibre1;
            if (distanciaLibre1 > distanciaLibre2 && distanciaLibre3 > distanciaLibre2) {
                distanciamenor = distanciaLibre2;

            } else if (distanciaLibre1 > distanciaLibre3 && distanciaLibre2 > distanciaLibre3) {

                distanciamenor = distanciaLibre3;
            }
//            System.out.println("Distancia Libre es : " + distanciamenor);
//            System.out.println("Errores a corregir : " + (2 * (Integer.parseInt(sltErroresCant.getSelectedItem().toString()))));
            if (distanciamenor >= (2 * (Integer.parseInt(sltErroresCant.getSelectedItem().toString())))) {
                resultado = true;
            } else {
                resultado = false;
                JOptionPane.showMessageDialog(null, "NO es posible corregir " + sltErroresCant.getSelectedItem().toString() + " errores en este sistema", "Mensaje de Advertencia", JOptionPane.WARNING_MESSAGE);
                JOptionPane.showMessageDialog(null, "A continuacion un sistema ideal para la cantidad de errores deseados", "Mensaje informativo", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            //No tiene salidas
            JOptionPane.showMessageDialog(null, "No se reconocen las salidas en el sistema ", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);

        }

        return resultado;
    }

    private void btnGenerarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarTablaActionPerformed
        this.fnCrearTabla();
        this.btnGenerarTabla.setEnabled(false);
        this.btnVerTabla.setEnabled(true);
        this.btnEstados.setEnabled(true);
        this.textMensaje.setEnabled(true);
        this.btnCodificar.setEnabled(true);
    }//GEN-LAST:event_btnGenerarTablaActionPerformed

    public String fnConvertirTextBit(String recibido) {
        //calculo el tamaño de la cadena
        int longitud = recibido.length();
        //creo un array char con el string anterior
        char cadChar[] = recibido.toCharArray();
        //inicializo varibles a utilizar en el ciclo
        String charBin = "";
        //ciclo que me convierte cada letra en binario
        for (int i = 0; i < cadChar.length; i++) {
            //convierto a binario cada caracter
            charBin += String.format("%8s", Integer.toBinaryString(cadChar[i])).replace(" ", "0");
        }
        return charBin;
    }

    public String fnConvertirBitText(String recibido) {
        int iResto = recibido.length() % 8;
        if (iResto > 0) {
            for (int i = 0; i < (8 - iResto); i++) {
                recibido += "0";
            }
        }
        //recibido += "00";
        String frase = "";//almacena la frase completa
        for (int i = 0; i < recibido.length(); i += 8) {//recorre la frase de 8 en 8
            /*separa la cadena cada 8 digitos con substring*/
            /*entrega un numero decimal a partir de un numero binario de 8 bit*/
            /*concadena la frase y transfroma el decimal a Ascii*/
            frase += (char) Integer.parseInt(recibido.substring(i, i + 8), 2);
        }
        return frase;
    }

    private void sltEcuacion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sltEcuacion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sltEcuacion2ActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (this.fnValidar() > 0) {
            boolean bValidacion = this.fnCrearEcuacion();
            if (bValidacion) {
                this.iCantEcuaciones = this.iCantEcuaciones + 1;
                this.jLabelNum.setText("Ecuacion #" + (this.iCantEcuaciones + 1));
                this.jError.setText("");
                this.jError1.setText("");
                this.sltEcuacion1.setSelectedIndex(0);
                this.sltEcuacion2.setSelectedIndex(0);
                this.sltEcuacion3.setSelectedIndex(0);
                this.sltEcuacion4.setSelectedIndex(0);
            } else {
                this.jError1.setText("Error: ");
                this.jError.setText("No se ha seleccionado los XOR correctos");
            }
        } else {
            this.jError1.setText("Error: ");
            this.jError.setText("Debe seleccionar elementos");
        }
        if (this.iCantEcuaciones == this.iSalida) {
            this.btnIngresar.setEnabled(false);
            this.btnGenerarTabla.setEnabled(true);
            this.sltEcuacion1.setEnabled(false);
            this.sltEcuacion2.setEnabled(false);
            this.sltEcuacion3.setEnabled(false);
            this.sltEcuacion4.setEnabled(false);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private boolean fnCrearEcuacion() {
        String sText = "";
        if (this.sltEcuacion1.getSelectedItem().toString() != "Ninguna") {
            if (sText == "") {
                sText += this.sltEcuacion1.getSelectedItem().toString();
            } else {
                sText += " XOR " + this.sltEcuacion1.getSelectedItem().toString();
            }
        }
        if (this.sltEcuacion2.getSelectedItem().toString() != "Ninguna") {
            if (sText == "") {
                sText += this.sltEcuacion2.getSelectedItem().toString();
            } else {
                sText += " XOR " + this.sltEcuacion2.getSelectedItem().toString();
            }
        }
        if (this.sltEcuacion3.getSelectedItem().toString() != "Ninguna") {
            if (sText == "") {
                sText += this.sltEcuacion3.getSelectedItem().toString();
            } else {
                sText += " XOR " + this.sltEcuacion3.getSelectedItem().toString();
            }
        }
        if (this.sltEcuacion4.getSelectedItem().toString() != "Ninguna") {
            if (sText == "") {
                sText += this.sltEcuacion4.getSelectedItem().toString();
            } else {
                sText += " XOR " + this.sltEcuacion4.getSelectedItem().toString();
            }
        }
        boolean bAux = false;
        aEcuacion[this.iCantEcuaciones] = sText;
        if ((this.iCantEcuaciones + 1) == this.iSalida) {
            String sXOR = "XOR";
            int iAux = 0;
            for (int i = 0; i < aEcuacion.length; i++) {
                if (aEcuacion[i].contains(sXOR)) {
                    iAux++;
                }
            }
            if (iAux != this.iXOR) {
                bAux = false;
            } else {
                bAux = true;
            }
        } else {
            bAux = true;
        }
        if (!bAux) {
            aEcuacion[this.iCantEcuaciones] = "";
        }
        return bAux;
    }

    private int fnValidar() {
        int iAux = 0;
        if (this.sltEcuacion1.getSelectedItem().toString() != "Ninguna") {
            iAux++;
        }
        if (this.sltEcuacion2.getSelectedItem().toString() != "Ninguna") {
            iAux++;
        }
        if (this.sltEcuacion3.getSelectedItem().toString() != "Ninguna") {
            iAux++;
        }
        if (this.sltEcuacion4.getSelectedItem().toString() != "Ninguna") {
            iAux++;
        }
        return iAux;
    }

    private void fnAgregarItems(javax.swing.JComboBox<String> eSelect) {
        eSelect.addItem("Ninguna");
        eSelect.addItem("E");
        for (int i = 0; i < this.iElementMemoria; i++) {
            eSelect.addItem("D" + (i + 1));
        }
    }

    private void fnAgregarItemsDec(javax.swing.JComboBox<String> eSelect, int iNumElem) {
        eSelect.removeAllItems();
        for (int i = 0; i < iNumElem; i++) {
            eSelect.addItem("" + (i + 1));
        }
    }

    private void btnVerTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTablaActionPerformed
        this.fnGenerarTabla();
    }//GEN-LAST:event_btnVerTablaActionPerformed

    private void fnReiniciar() {
        this.cmbElementosDeMemoria.setEnabled(true);
        this.sltXor.setEnabled(true);
        this.sltSalidas.setEnabled(true);
        this.btnCapturar.setEnabled(true);
        this.sltEcuacion1.setEnabled(false);
        this.sltEcuacion2.setEnabled(false);
        this.sltEcuacion3.setEnabled(false);
        this.sltEcuacion4.setEnabled(false);
        this.textBit.setEnabled(false);
        this.textCodificado.setEnabled(false);
        this.cmbElementosDeMemoria.setSelectedIndex(0);
        this.sltXor.setSelectedIndex(0);
        this.sltSalidas.setSelectedIndex(0);
        this.sltEcuacion1.setSelectedIndex(0);
        this.sltEcuacion2.setSelectedIndex(0);
        this.sltEcuacion3.setSelectedIndex(0);
        this.sltEcuacion4.setSelectedIndex(0);
        this.btnIngresar.setEnabled(false);
        this.btnGenerarTabla.setEnabled(false);
        this.textMensaje.setEnabled(false);
        this.btnCodificar.setEnabled(false);
        this.btnVerTabla.setEnabled(false);
        this.btnEstados.setEnabled(false);
        this.txtDecodificado.setEnabled(false);
        this.txtEstadosSalidas.setEnabled(false);
        this.sltPalabras.setEnabled(false);
        this.sltErroresCant.setEnabled(false);
        this.txtAreaMsgError.setEnabled(false);
        this.txtAreaMsgCorre.setEnabled(false);
        this.txtAreaMsgSol.setEnabled(false);
        this.txtAreaMsgError.setText("");
        this.txtAreaMsgCorre.setText("");
        this.txtAreaMsgSol.setText("");
        this.btnReiniciarDec.setEnabled(false);
        this.btnCapturarDec.setEnabled(false);
        this.btnCorrerDec.setEnabled(false);
        this.btnDecodificar.setEnabled(false);
        this.jLabelNum.setText("Ecuacion #1");
        this.textMensaje.setText("");
        this.textBit.setText("");
        this.textCodificado.setText("");
        this.txtDecodificado.setText("");
        this.txtEstadosSalidas.setText("");
        this.iCantEcuaciones = 0;
        this.jError.setText("");
        this.jError1.setText("");
    }

    private void btnCodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodificarActionPerformed
        if (this.textMensaje.getText() != "") {
            this.fnAgregarItemsDec(this.sltPalabras, this.textMensaje.getText().length());
            this.sltPalabras.setEnabled(true);
            this.sltErroresCant.setEnabled(true);
            this.btnReiniciarDec.setEnabled(true);
            this.btnCapturarDec.setEnabled(true);
            String sBinario = this.fnConvertirTextBit(this.textMensaje.getText());
            this.textBit.setText(sBinario);
            this.textCodificado.setText(this.oFec.getCodificar(sBinario));
            this.sTextBitCod = this.textCodificado.getText().replace("~", "");
            this.sTextBitCod = this.sTextBitCod.substring(0, this.sTextBitCod.length() - this.iSalida);
            this.txtEstadosSalidas.setText(this.oFec.getEstadosFinales());
            this.txtDecodificado.setText(this.fnConvertirBitText(this.oFec.getsCodificado()));
        }
        this.fnReiniciarDeco();
    }//GEN-LAST:event_btnCodificarActionPerformed

    private void btnEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadosActionPerformed
        DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        this.tableEstados.setModel(modelo);
        int iEstados = (int) pow(2, this.iElementMemoria);
        // For para imprimir la matriz de prueba
        for (int i = 0; i < iEstados; i++) {
            modelo.addColumn("S°" + i);
        }
        Object[] fila = new Object[iEstados];
        for (int i = 0; i < this.iEstados.length; i++) {
            fila[i] = this.iEstados[i];
        }
        modelo.addRow(fila);
        this.jDialogEstados.show();
    }//GEN-LAST:event_btnEstadosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.fnReiniciar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarActionPerformed
        this.iElementMemoria = Integer.parseInt(this.cmbElementosDeMemoria.getSelectedItem().toString());
        this.iXOR = Integer.parseInt(this.sltXor.getSelectedItem().toString());
        this.iSalida = Integer.parseInt(this.sltSalidas.getSelectedItem().toString());
        aEcuacion = new String[this.iSalida];
        this.btnIngresar.setEnabled(true);
        this.cmbElementosDeMemoria.setEnabled(false);
        this.sltXor.setEnabled(false);
        this.sltSalidas.setEnabled(false);
        this.btnCapturar.setEnabled(false);
        this.sltEcuacion1.setEnabled(true);
        this.sltEcuacion2.setEnabled(true);
        this.sltEcuacion3.setEnabled(true);
        this.sltEcuacion4.setEnabled(true);
        this.sltEcuacion1.removeAllItems();
        this.sltEcuacion2.removeAllItems();
        this.sltEcuacion3.removeAllItems();
        this.sltEcuacion4.removeAllItems();
        this.fnAgregarItems(this.sltEcuacion1);
        this.fnAgregarItems(this.sltEcuacion2);
        this.fnAgregarItems(this.sltEcuacion3);
        this.fnAgregarItems(this.sltEcuacion4);
    }//GEN-LAST:event_btnCapturarActionPerformed

    private void sltXorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sltXorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sltXorActionPerformed

    private void cmbElementosDeMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbElementosDeMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbElementosDeMemoriaActionPerformed

    private void btnReiniciarDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarDecActionPerformed
        this.fnReiniciarDeco();
    }//GEN-LAST:event_btnReiniciarDecActionPerformed

    private void fnReiniciarDeco() {
        try {
            this.fnAgregarItemsDec(this.sltErroresCant, 3);
            this.sltPalabras.setEnabled(true);
            this.sltErroresCant.setEnabled(true);
            this.sltPalabras.setSelectedIndex(0);
            this.sltErroresCant.setSelectedIndex(0);
            this.txtAreaMsgError.setText("");
            this.txtAreaMsgCorre.setText("");
            this.txtAreaMsgSol.setText("");
            this.btnCapturarDec.setEnabled(true);
            this.btnCorrerDec.setEnabled(false);
            this.btnDecodificar.setEnabled(false);
            this.iCapturaErrores = 0;
            this.sTextBitCod = this.textCodificado.getText().replace("~", "");
            this.sTextBitCod = this.sTextBitCod.substring(0, this.sTextBitCod.length() - this.iSalida);
            this.jlblNumErrores.setText("Errores #0");
        } catch (Exception e) {
        }
    }

    private void btnCapturarDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarDecActionPerformed

        if (distanciaLibre()) {
            String sAux = "";
            if (3 != this.iCapturaErrores) {
                this.iCapturaErrores = this.iCapturaErrores + Integer.parseInt(this.sltErroresCant.getSelectedItem().toString());
                for (int i = 0; i < Integer.parseInt(this.sltErroresCant.getSelectedItem().toString()); i++) {
                    int iAux = (int) (Math.random() * 8);
                    int iPosicion = ((Integer.parseInt(this.sltPalabras.getSelectedItem().toString()) - 1) * 8) + iAux;
                    if ((iPosicion + 1) > this.sTextBitCod.length()) {
                        sAux = this.sTextBitCod.substring(iPosicion, this.sTextBitCod.length());
                    } else {
                        sAux = this.sTextBitCod.substring(iPosicion, iPosicion + 1);
                    }
                    String sModificado = "";
                    if (sAux.equals("0")) {
                        sAux = "1";
                    } else {
                        sAux = "0";
                    }
                    if ((iPosicion - 1) < 0) {
                        this.sTextBitCod = sAux + this.sTextBitCod.substring(1, this.sTextBitCod.length());
                    } else {
                        this.sTextBitCod = this.sTextBitCod.substring(0, iPosicion) + sAux + this.sTextBitCod.substring(iPosicion + 1, this.sTextBitCod.length());
                    }
                }
                this.jlblNumErrores.setText("Errores #" + this.iCapturaErrores);
                this.btnCorrerDec.setEnabled(true);
                String sAux2 = this.sTextBitCod;
                for (int j = 0; j < this.iSalida; j++) {
                    sAux2 += "0";
                }
                this.txtAreaMsgError.setText(sAux2);
                if ((3 - this.iCapturaErrores) > 0) {
                    this.fnAgregarItemsDec(this.sltErroresCant, 3 - this.iCapturaErrores);
                    this.sltErroresCant.setSelectedIndex(0);
                } else {
                    this.sltPalabras.setEnabled(false);
                    this.sltErroresCant.setEnabled(false);
                    this.btnCapturarDec.setEnabled(false);
                }
            }
        } else {

//System.out.println("El sistema NO puede corregir " + sltErroresCant.getSelectedItem() + " errores...");
            if (sltErroresCant.getSelectedItem().toString().equals("1")) {
                String mensaje = "Configuración:\n"
                        + "2 salidas\n"
                        + "1 elementos de memoria\n"
                        + "2 XOR\n"
                        + "\n"
                        + "Ecuaciones:\n"
                        + "s1 = E XOR D1 \n"
                        + "s2= D1 XOR E";
                this.txtPropuesta.setText(mensaje);
                this.jDialogPropuesta.show();
            } else if (sltErroresCant.getSelectedItem().toString().equals("2")) {
                String mensaje = "Configuración:\n"
                        + "2 salidas\n"
                        + "2 elementos de memoria\n"
                        + "2 XOR\n"
                        + "\n"
                        + "Ecuaciones:\n"
                        + "s1 = E XOR D1 XOR D2\n"
                        + "s2= E XOR D2";
                this.txtPropuesta.setText(mensaje);
                this.jDialogPropuesta.show();
            } else {
                String mensaje = "Configuración:\n"
                        + "2 salidas\n"
                        + "3 elementos de memoria\n"
                        + "1 XOR\n"
                        + "\n"
                        + "Ecuaciones:\n"
                        + "s1 = E XOR D1 \n"
                        + "s2= D2";
                this.txtPropuesta.setText(mensaje);
                this.jDialogPropuesta.show();
            }
        }

    }//GEN-LAST:event_btnCapturarDecActionPerformed

    private void btnCorrerDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrerDecActionPerformed
        this.txtAreaMsgCorre.setText(this.oFec.getVitterbi(this.sTextBitCod));
        this.btnDecodificar.setEnabled(true);
    }//GEN-LAST:event_btnCorrerDecActionPerformed

    private void btnDecodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecodificarActionPerformed
        String sEntradas = this.oFec.getsDecodificacion();
        this.txtAreaMsgSol.setText(this.fnConvertirBitText(sEntradas));
    }//GEN-LAST:event_btnDecodificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JDialogTablaVerdad;
    private javax.swing.JTabbedPane JPanelContenedor;
    private javax.swing.JButton btnCapturar;
    private javax.swing.JButton btnCapturarDec;
    private javax.swing.JButton btnCodificar;
    private javax.swing.JButton btnCorrerDec;
    private javax.swing.JButton btnDecodificar;
    private javax.swing.JButton btnEstados;
    private javax.swing.JButton btnGenerarTabla;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnReiniciarDec;
    private javax.swing.JButton btnVerTabla;
    private javax.swing.JComboBox<String> cmbElementosDeMemoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialogEstados;
    private javax.swing.JDialog jDialogPropuesta;
    private javax.swing.JLabel jError;
    private javax.swing.JLabel jError1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelEcuaciones;
    private javax.swing.JPanel jPanelMensaje;
    private javax.swing.JPanel jPanelVariables;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel jlblNumErrores;
    private javax.swing.JComboBox<String> sltEcuacion1;
    private javax.swing.JComboBox<String> sltEcuacion2;
    private javax.swing.JComboBox<String> sltEcuacion3;
    private javax.swing.JComboBox<String> sltEcuacion4;
    private javax.swing.JComboBox<String> sltErroresCant;
    private javax.swing.JComboBox<String> sltPalabras;
    private javax.swing.JComboBox<String> sltSalidas;
    private javax.swing.JComboBox<String> sltXor;
    private javax.swing.JTable tableEstados;
    private javax.swing.JTable tableTVerdad;
    private javax.swing.JTextArea textBit;
    private javax.swing.JTextArea textCodificado;
    private javax.swing.JTextArea textMensaje;
    private javax.swing.JTextArea txtAreaMsgCorre;
    private javax.swing.JTextArea txtAreaMsgError;
    private javax.swing.JTextArea txtAreaMsgSol;
    private javax.swing.JTextArea txtDecodificado;
    private javax.swing.JTextArea txtEstadosSalidas;
    private javax.swing.JTextArea txtPropuesta;
    // End of variables declaration//GEN-END:variables

}
